"""
tests/test_guardrails.py
"""

import pytest
from pydantic import ValidationError
from serving_layer.guardrails.prompts import (
    LLMAdverseAction,
    parse_and_validate_llm_output,
)


def test_valid_llm_adverse_action():
    """Verifies that compliant LLM explanations pass validation."""
    data = {
        "feature_name": "revolving_utilization",
        "human_readable_reason": "High revolving balances relative to overall credit limits.",
    }
    action = LLMAdverseAction(**data)
    assert action.feature_name == "revolving_utilization"


@pytest.mark.parametrize("prohibited_word", ["zip code", "gender", "race", "marital status"])
def test_fair_lending_prohibited_terms_rejected(prohibited_word):
    """Ensures Pydantic validator catches protected class terms generated by an LLM."""
    data = {
        "feature_name": "risk_factor",
        "human_readable_reason": f"High risk factor associated with consumer {prohibited_word}.",
    }
    with pytest.raises(ValidationError) as exc_info:
        LLMAdverseAction(**data)

    assert "FAIR LENDING VIOLATION" in str(exc_info.value)


def test_parse_and_validate_llm_output_fallback_on_violation():
    """Tests that invalid or non-compliant raw JSON falls back to a safe compliant response."""
    illegal_json = '{"feature_name": "test", "human_readable_reason": "Denied due to zip code history."}'
    res = parse_and_validate_llm_output(illegal_json)

    assert res.feature_name == "compliance_override"
    assert "Standardized fallback" in res.human_readable_reason


def test_parse_and_validate_llm_output_fallback_on_malformed_json():
    """Tests handling of malformed JSON strings from an LLM."""
    malformed_json = '{"feature_name": "test", "human_readable_reason": ...}'
    res = parse_and_validate_llm_output(malformed_json)

    assert res.feature_name == "unknown"
    assert "system format error" in res.human_readable_reason